### ISSUE TITLE
✨ Feature: Wallet Integration

### ISSUE THREAD

**Issue by PhearZero** [algodex/algodex-hooks#3]
# ℹ Overview
- Milestone: Algodex Support for more wallet types
- Milestone: Launch of trading SDK for Algodex 

Adds multi-wallet support as a part of the hooks library. This handles state setters and assigns the available wallets. 

### 📝 Related Issues

- [x] algodex/algodex-react#176
- [x] algodex/algodex-sdk#125
- [x] algodex/algodex-react#431
- [ ] algodex/algodex-react#423
